"""added a date created

Revision ID: 53c0c5391dd3
Revises: b74f584869c8
Create Date: 2025-01-10 17:46:31.752089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c0c5391dd3'
down_revision = 'b74f584869c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
